INSERT INTO `planet`(`id`, `name`, `climate`, `terrain`) VALUES 
(1, 'Tatooine', 'arid', 'desert'),
(2, 'Alderaan', 'temperate', 'grasslands, mountains'),
(3, 'Yavin IV', 'temperate, tropical', 'jungle, rainforests'),
(4, 'Hoth', 'frozen', 'tundra, ice caves, mountain ranges'),
(5, 'Dagobah', 'murky', 'swamp, jungles'),
(6, 'Bespin', 'temperate', 'gas giant'),
(7, 'Endor', 'temperate', 'forests, mountains, lakes'),
(8, 'Naboo', 'temperate', 'grassy hills, swamps, forests'),
(9, 'Coruscant', 'temperate', 'cityscape, mountains'),
(10, 'Kamino', 'temperate', 'ocean'),
(11, 'Geonosis', 'temperate, arid', 'rock, desert, mountain, barren'),
(12, 'Utapau', 'temperate, arid, windy', 'scrublands, savanna, canyons, sinkholes'),
(13, 'Mustafar', 'hot', 'volcanoes, lava rivers, mountains, caves'),
(14, 'Kashyyyk', 'tropical', 'jungle, forests, lakes, rivers'),
(15, 'Polis Massa', 'artificial temperate', 'airless asteroid'),
(16, 'Mygeeto', 'frigid', 'glaciers, mountains, ice canyons'),
(17, 'Felucia', 'hot, humid', 'fungus forests'),
(18, 'Cato Neimoidia', 'temperate, moist', 'mountains, fields, forests, rock arches'),
(19, 'Saleucami', 'hot', 'caves, desert, mountains, volcanoes'),
(20, 'Stewjon', 'temperate', 'grass'),
(21, 'Eriadu', 'polluted', 'polluted'),
(22, 'Corellia', 'temperate', 'plains, urban, hills, forests'),
(23, 'Rodia', 'hot', 'jungles, oceans, urban, swamps'),
(24, 'Nal Hutta', 'temperate', 'urban, oceans, swamps, bogs');